# Generated by Django 3.1.2 on 2021-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210307_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
